title: Doric
subtitle: "Doric is a cross-platform development framework for Android & iOS & H5 & Qt."
description: "Cross-platform development framework"
author: Zhou Pengfei
language: en
timezone: UTC

url: https://doric.pub
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0
pretty_urls:
  trailing_index: false
  trailing_html: false

theme: navy

highlight:
  enable: true
  line_number: false

github: doric-pub/Doric

deploy:
  type: "git"
  repo: "git@github.com:doric-pub/DoricDocs.git"
